sudo: required

language: generic

services:
  - docker

before_install:
  - travis_wait 20 docker build -t agda-docker .

#  /home/travis/build/ernius/genericBindingFramework
script:
  - wget https://github.com/agda/agda-stdlib/archive/v0.13.tar.gz -O /tmp/v0.13.tar.gz
  - tar -xzvf /tmp/v0.13.tar.gz -C /tmp/
  - echo $TRAVIS_BUILD_DIR
#  - docker run agda-docker /bin/sh -c 'pwd;ls -lh;ls -lh /home/travis/build/ernius/'
#  - travis_wait docker run agda-docker agda --version
#  - travis_wait docker run -v $TRAVIS_BUILD_DIR:/tmp/project-build -v /tmp:/tmp/agdalibrary agda-docker /bin/sh -c 'cd /tmp/project-build; agda -i . -i /tmp/agdalibrary/agda-stdlib-0.13/src/ Examples/SystemF.lagda'
  - docker run -v $TRAVIS_BUILD_DIR:/tmp/project-build -v /tmp:/tmp/agdalibrary agda-docker /bin/sh -c 'cd /tmp/project-build; agda -i . -i /tmp/agdalibrary/agda-stdlib-0.13/src/ Examples/SystemF.lagda'