sudo: required

language: generic

services:
  - docker

before_install:
  - docker build .

script:
#  - whoami travis
#  - pwd /home/travis/build/ernius/genericBindingFramework
  - echo $PATH
  - /tmp/agda -i . -i /tmp/agda-stdlib-0.13/src/ ./Examples/SystemF.lagda
