sudo: required

language: generic

services:
  - docker

before_install:
  - docker build .

script:
  - whoami
  - pwd
  - ls -a
  - echo $PATH
  - /tmp/agda -i . -i /tmp/agda-stdlib-0.13/src/ ./Examples/SystemF.lagda
