sudo: required

language: generic

services:
  - docker

before_install:
  - travis_wait 30 docker build -t agda-docker .

#  /home/travis/build/ernius/genericBindingFramework
script:
  - wget https://github.com/agda/agda-stdlib/archive/v0.13.tar.gz -O /tmp/v0.13.tar.gz
  - tar -xzvf /tmp/v0.13.tar.gz -C /tmp/
  - docker run agda-docker /bin/sh -c 'pwd;ls -lh;ls -lh /home/travis/build/ernius/'
  - travis_wait docker run agda-docker agda --version
  - travis_wait docker run agda-docker agda -i /home/travis/build/ernius/genericBindingFramework/ -i /tmp/agda-stdlib-0.13/src/ /home/travis/build/ernius/genericBindingFramework/Examples/SystemF.lagda
